"""UI related changes

Revision ID: 6e601450b7b8
Revises: 
Create Date: 2025-11-10 19:11:13.145521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e601450b7b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_settings_dates_idx'), table_name='user_settings', postgresql_with={'deduplicate_items': 'true'})
    op.drop_index(op.f('user_settings_uid'), table_name='user_settings', postgresql_with={'deduplicate_items': 'false'})
    op.drop_table('user_settings')
    op.drop_table('user_profiles_del')
    op.drop_index(op.f('rates_dates_idx'), table_name='rates', postgresql_with={'deduplicate_items': 'true'})
    op.drop_index(op.f('rates_ipid_idx'), table_name='rates', postgresql_with={'deduplicate_items': 'false'})
    op.drop_table('rates')
    op.drop_index(op.f('endpoints_idx'), table_name='endpoints', postgresql_with={'deduplicate_items': 'true'})
    op.drop_table('endpoints')
    op.drop_table('endpoint_logs')
    op.drop_table('tn2lrn216')
    op.drop_table('products')
    op.drop_table('endpoint_stats')
    op.drop_table('user_profiles')
    op.alter_column('lerg6', 'lata',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('lerg6', 'blockid',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('lerg6', 'ocn',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('lerg6', 'line_fr',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(),
               nullable=False)
    op.alter_column('lerg6', 'line_to',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(),
               nullable=False)
    op.alter_column('lerg6', 'lata3',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(),
               nullable=False)
    op.alter_column('lerg6', 'switch',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('lerg6', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('lerg6', 'rc',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('lerg6', 'ocnname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('lerg6', 'category',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('lerg6', 'co_spec_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('lerg6', 'lataname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('lerg6', 'locality',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('lerg6_npanxxx_idx'), table_name='lerg6', postgresql_with={'deduplicate_items': 'true'})
    op.drop_index(op.f('lerg6i'), table_name='lerg6')
    op.drop_index(op.f('lerg6i1'), table_name='lerg6')
    op.create_index(op.f('ix_lerg6_npanxxx'), 'lerg6', ['npanxxx'], unique=False)
    op.drop_column('lerg6', 'sync')
    op.alter_column('local', 'from_rc_abbrev',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('local', 'from_state',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('local', 'from_lata',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('local', 'to_rc_abbrev',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('local', 'to_state',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('local', 'to_lata',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.drop_index(op.f('local_idx'), table_name='local')
    op.create_index(op.f('ix_local_from_lata'), 'local', ['from_lata'], unique=False)
    op.create_index(op.f('ix_local_from_rc_abbrev'), 'local', ['from_rc_abbrev'], unique=False)
    op.create_index(op.f('ix_local_from_state'), 'local', ['from_state'], unique=False)
    op.create_index(op.f('ix_local_to_lata'), 'local', ['to_lata'], unique=False)
    op.create_index(op.f('ix_local_to_rc_abbrev'), 'local', ['to_rc_abbrev'], unique=False)
    op.create_index(op.f('ix_local_to_state'), 'local', ['to_state'], unique=False)
    op.drop_column('local', 'sync')
    op.alter_column('nnmp', 'nnmp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_nnmp_co_spec_name'), 'nnmp', ['co_spec_name'], unique=False)
    op.alter_column('numberpoolblock', 'mibcreatetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('numberpoolblock', 'mibupdatetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('numberpoolblock', 'objectclass',
               existing_type=sa.VARCHAR(length=15),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'namebinding',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'numberpoolblockid',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('numberpoolblock', 'spid',
               existing_type=sa.VARCHAR(length=4),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'activationtimestamp',
               existing_type=sa.VARCHAR(length=17),
               nullable=False)
    op.alter_column('numberpoolblock', 'class_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'class_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'lidb_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'lidb_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'cnam_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'cnam_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'isvm_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'isvm_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'wsmsc_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'wsmsc_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'blocksvtype',
               existing_type=sa.VARCHAR(length=24),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'downloadreason',
               existing_type=sa.VARCHAR(length=17),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'altspid',
               existing_type=sa.VARCHAR(length=4),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'alteult',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'alteulv',
               existing_type=sa.VARCHAR(length=12),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'altbid',
               existing_type=sa.VARCHAR(length=4),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'voiceuri',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'mmsuri',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'smsuri',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index(op.f('ix_numberpoolblock_npanxxx'), 'numberpoolblock', ['npanxxx'], unique=False)
    op.create_index(op.f('ix_simple_carrier_names_co_spec_name'), 'simple_carrier_names', ['co_spec_name'], unique=False)
    op.create_index(op.f('ix_spidnames_spid'), 'spidnames', ['spid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spidnames_spid'), table_name='spidnames')
    op.drop_index(op.f('ix_simple_carrier_names_co_spec_name'), table_name='simple_carrier_names')
    op.drop_index(op.f('ix_numberpoolblock_npanxxx'), table_name='numberpoolblock')
    op.alter_column('numberpoolblock', 'smsuri',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'mmsuri',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'voiceuri',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'altbid',
               existing_type=sa.VARCHAR(length=4),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'alteulv',
               existing_type=sa.VARCHAR(length=12),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'alteult',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'altspid',
               existing_type=sa.VARCHAR(length=4),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'downloadreason',
               existing_type=sa.VARCHAR(length=17),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'blocksvtype',
               existing_type=sa.VARCHAR(length=24),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'wsmsc_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'wsmsc_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'isvm_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'isvm_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'cnam_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'cnam_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'lidb_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'lidb_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'class_ssn',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'class_dpc',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'activationtimestamp',
               existing_type=sa.VARCHAR(length=17),
               nullable=True)
    op.alter_column('numberpoolblock', 'spid',
               existing_type=sa.VARCHAR(length=4),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'numberpoolblockid',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('numberpoolblock', 'namebinding',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'objectclass',
               existing_type=sa.VARCHAR(length=15),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('numberpoolblock', 'mibupdatetime',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('numberpoolblock', 'mibcreatetime',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_nnmp_co_spec_name'), table_name='nnmp')
    op.alter_column('nnmp', 'nnmp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('local', sa.Column('sync', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_local_to_state'), table_name='local')
    op.drop_index(op.f('ix_local_to_rc_abbrev'), table_name='local')
    op.drop_index(op.f('ix_local_to_lata'), table_name='local')
    op.drop_index(op.f('ix_local_from_state'), table_name='local')
    op.drop_index(op.f('ix_local_from_rc_abbrev'), table_name='local')
    op.drop_index(op.f('ix_local_from_lata'), table_name='local')
    op.create_index(op.f('local_idx'), 'local', ['from_rc_abbrev', 'from_lata', 'from_state', 'to_state', 'to_lata', 'to_rc_abbrev'], unique=False)
    op.alter_column('local', 'to_lata',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('local', 'to_state',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('local', 'to_rc_abbrev',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('local', 'from_lata',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('local', 'from_state',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('local', 'from_rc_abbrev',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.add_column('lerg6', sa.Column('sync', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_lerg6_npanxxx'), table_name='lerg6')
    op.create_index(op.f('lerg6i1'), 'lerg6', ['sync'], unique=False)
    op.create_index(op.f('lerg6i'), 'lerg6', ['npanxx', 'blockid'], unique=False)
    op.create_index(op.f('lerg6_npanxxx_idx'), 'lerg6', ['npanxxx'], unique=True, postgresql_with={'deduplicate_items': 'true'})
    op.alter_column('lerg6', 'locality',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('lerg6', 'lataname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('lerg6', 'co_spec_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('lerg6', 'category',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('lerg6', 'ocnname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('lerg6', 'rc',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('lerg6', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('lerg6', 'switch',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('lerg6', 'lata3',
               existing_type=sa.String(),
               type_=sa.CHAR(length=3),
               nullable=True)
    op.alter_column('lerg6', 'line_to',
               existing_type=sa.String(),
               type_=sa.CHAR(length=4),
               nullable=True)
    op.alter_column('lerg6', 'line_fr',
               existing_type=sa.String(),
               type_=sa.CHAR(length=4),
               nullable=True)
    op.alter_column('lerg6', 'ocn',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('lerg6', 'blockid',
               existing_type=sa.String(),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.alter_column('lerg6', 'lata',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_profiles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('isactive', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('issuperuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('datecreated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('datedeactivated', postgresql.TIMESTAMP(), server_default=sa.text("'2222-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('endpoint_stats',
    sa.Column('calldate', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpointid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('calldate', 'userid', 'endpointid', name=op.f('endpoint_stats_pkey'))
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('productname', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tn2lrn216',
    sa.Column('mibcreatetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('mibupdatetime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tn', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('lrn', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('spid', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('activationtimestamp', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('class_dpc', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('class_ssn', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('lidb_dpc', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('lidb_ssn', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('cnam_dpc', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('cnam_ssn', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('isvm_dpc', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('isvm_ssn', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('wsmsc_dpc', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('wsmsc_ssn', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('enduserlocationvalue', sa.VARCHAR(length=12), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('enduserlocationtype', sa.VARCHAR(length=2), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('billingid', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('lnptype', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('downloadreason', sa.VARCHAR(length=17), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('svtype', sa.VARCHAR(length=24), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('altspid', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('alteult', sa.VARCHAR(length=2), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('alteulv', sa.VARCHAR(length=12), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('altbid', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('voiceuri', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('mmsuri', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('smsuri', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tn', name=op.f('tn2lrn216_pk'))
    )
    op.create_table('endpoint_logs',
    sa.Column('event_date', postgresql.ARRAY(postgresql.TIME()), autoincrement=False, nullable=False),
    sa.Column('ip-address', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('return', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('from', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('to', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('eventid', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('eventid', name=op.f('endpoint_logs_pkey'))
    )
    op.create_table('endpoints',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('endpoints_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='endpoints_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('endpoints_idx'), 'endpoints', ['endpoint'], unique=True, postgresql_with={'deduplicate_items': 'true'})
    op.create_table('rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpointid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('dateeff', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dateexp', postgresql.TIMESTAMP(), server_default=sa.text("'2222-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpointid'], ['endpoints.id'], name=op.f('rates_endpoint_fk')),
    sa.ForeignKeyConstraint(['productid'], ['products.id'], name=op.f('rates_productid_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('rates_pkey'))
    )
    op.create_index(op.f('rates_ipid_idx'), 'rates', ['endpointid'], unique=False, postgresql_with={'deduplicate_items': 'false'})
    op.create_index(op.f('rates_dates_idx'), 'rates', ['dateeff', 'dateexp'], unique=False, postgresql_with={'deduplicate_items': 'true'})
    op.create_table('user_profiles_del',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('isactive', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('issuperuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('datecreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('datedeactivated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('datedeleted', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_del_pkey'))
    )
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('ratio', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('productpriority', sa.SMALLINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('dateeff', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dateexp', postgresql.TIMESTAMP(), server_default=sa.text("'2222-01-01 00:00:00'::timestamp without time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['productid'], ['products.id'], name=op.f('user_settings_productid_fk')),
    sa.ForeignKeyConstraint(['userid'], ['user_profiles.id'], name=op.f('user_settings_userid_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_settings_pkey'))
    )
    op.create_index(op.f('user_settings_uid'), 'user_settings', ['userid'], unique=False, postgresql_with={'deduplicate_items': 'false'})
    op.create_index(op.f('user_settings_dates_idx'), 'user_settings', ['dateeff', 'dateexp'], unique=False, postgresql_with={'deduplicate_items': 'true'})
    # ### end Alembic commands ###
