"""empty message

Revision ID: 990099fb2b9a
Revises: 
Create Date: 2025-08-19 17:54:43.502135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990099fb2b9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lerg6',
    sa.Column('npanxxx', sa.String(), nullable=False),
    sa.Column('lata', sa.String(), nullable=False),
    sa.Column('npanxx', sa.String(), nullable=False),
    sa.Column('blockid', sa.String(), nullable=False),
    sa.Column('ocn', sa.String(), nullable=False),
    sa.Column('line_fr', sa.String(), nullable=False),
    sa.Column('line_to', sa.String(), nullable=False),
    sa.Column('lata3', sa.String(), nullable=False),
    sa.Column('switch', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('rc', sa.String(), nullable=False),
    sa.Column('ocnname', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('co_spec_name', sa.String(), nullable=False),
    sa.Column('lataname', sa.String(), nullable=False),
    sa.Column('locality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('npanxxx')
    )
    op.create_index(op.f('ix_lerg6_npanxxx'), 'lerg6', ['npanxxx'], unique=False)
    op.create_table('local',
    sa.Column('from_rc_abbrev', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('from_lata', sa.String(), nullable=False),
    sa.Column('to_rc_abbrev', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('to_lata', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('from_rc_abbrev', 'from_state', 'from_lata', 'to_rc_abbrev', 'to_state', 'to_lata')
    )
    op.create_table('nnmp',
    sa.Column('co_spec_name', sa.String(), nullable=False),
    sa.Column('nnmp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('co_spec_name')
    )
    op.create_index(op.f('ix_nnmp_co_spec_name'), 'nnmp', ['co_spec_name'], unique=False)
    op.create_table('numberpoolblock',
    sa.Column('mibcreatetime', sa.String(), nullable=False),
    sa.Column('mibupdatetime', sa.String(), nullable=False),
    sa.Column('objectclass', sa.String(), nullable=False),
    sa.Column('namebinding', sa.String(), nullable=False),
    sa.Column('numberpoolblockid', sa.Integer(), nullable=False),
    sa.Column('npanxxx', sa.String(), nullable=False),
    sa.Column('spid', sa.String(), nullable=False),
    sa.Column('activationtimestamp', sa.String(), nullable=False),
    sa.Column('lrn', sa.String(), nullable=False),
    sa.Column('class_dpc', sa.String(), nullable=False),
    sa.Column('class_ssn', sa.String(), nullable=False),
    sa.Column('lidb_dpc', sa.String(), nullable=False),
    sa.Column('lidb_ssn', sa.String(), nullable=False),
    sa.Column('cnam_dpc', sa.String(), nullable=False),
    sa.Column('cnam_ssn', sa.String(), nullable=False),
    sa.Column('isvm_dpc', sa.String(), nullable=False),
    sa.Column('isvm_ssn', sa.String(), nullable=False),
    sa.Column('wsmsc_dpc', sa.String(), nullable=False),
    sa.Column('wsmsc_ssn', sa.String(), nullable=False),
    sa.Column('blocksvtype', sa.String(), nullable=False),
    sa.Column('downloadreason', sa.String(), nullable=False),
    sa.Column('altspid', sa.String(), nullable=False),
    sa.Column('alteult', sa.String(), nullable=False),
    sa.Column('alteulv', sa.String(), nullable=False),
    sa.Column('altbid', sa.String(), nullable=False),
    sa.Column('voiceuri', sa.String(), nullable=False),
    sa.Column('mmsuri', sa.String(), nullable=False),
    sa.Column('smsuri', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('npanxxx')
    )
    op.create_index(op.f('ix_numberpoolblock_npanxxx'), 'numberpoolblock', ['npanxxx'], unique=False)
    op.create_table('simple_carrier_names',
    sa.Column('co_spec_name', sa.String(), nullable=False),
    sa.Column('simplified_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('co_spec_name')
    )
    op.create_index(op.f('ix_simple_carrier_names_co_spec_name'), 'simple_carrier_names', ['co_spec_name'], unique=False)
    op.create_table('spidnames',
    sa.Column('spid', sa.String(), nullable=False),
    sa.Column('spidname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('spid')
    )
    op.create_index(op.f('ix_spidnames_spid'), 'spidnames', ['spid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spidnames_spid'), table_name='spidnames')
    op.drop_table('spidnames')
    op.drop_index(op.f('ix_simple_carrier_names_co_spec_name'), table_name='simple_carrier_names')
    op.drop_table('simple_carrier_names')
    op.drop_index(op.f('ix_numberpoolblock_npanxxx'), table_name='numberpoolblock')
    op.drop_table('numberpoolblock')
    op.drop_index(op.f('ix_nnmp_co_spec_name'), table_name='nnmp')
    op.drop_table('nnmp')
    op.drop_table('local')
    op.drop_index(op.f('ix_lerg6_npanxxx'), table_name='lerg6')
    op.drop_table('lerg6')
    # ### end Alembic commands ###
