"""empty message

Revision ID: b8954a45b759
Revises: 990099fb2b9a
Create Date: 2025-08-20 16:14:16.689073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8954a45b759'
down_revision: Union[str, Sequence[str], None] = '990099fb2b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_local_from_lata'), 'local', ['from_lata'], unique=False)
    op.create_index(op.f('ix_local_from_rc_abbrev'), 'local', ['from_rc_abbrev'], unique=False)
    op.create_index(op.f('ix_local_from_state'), 'local', ['from_state'], unique=False)
    op.create_index(op.f('ix_local_to_lata'), 'local', ['to_lata'], unique=False)
    op.create_index(op.f('ix_local_to_rc_abbrev'), 'local', ['to_rc_abbrev'], unique=False)
    op.create_index(op.f('ix_local_to_state'), 'local', ['to_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_to_state'), table_name='local')
    op.drop_index(op.f('ix_local_to_rc_abbrev'), table_name='local')
    op.drop_index(op.f('ix_local_to_lata'), table_name='local')
    op.drop_index(op.f('ix_local_from_state'), table_name='local')
    op.drop_index(op.f('ix_local_from_rc_abbrev'), table_name='local')
    op.drop_index(op.f('ix_local_from_lata'), table_name='local')
    # ### end Alembic commands ###
