#!/bin/perl
#
# This script creates a partitioned table for uiadmin logs in PostgreSQL
#
use strict;
use DBI;
use POSIX qw(strftime);

my $workDir='/builds/vkhrenov-group/routeAPI';
my $fromdate=$ARGV[0];
my $todate=$ARGV[1];
my $date;
my $uidb="dbi:Pg:dbname=EndpointLogs;host=localhost;port=5433";
my $password=""; 

$fromdate=strftime('%Y-%m-%d', localtime(time + 86400)) unless ($fromdate);
$todate=strftime('%Y-%m-%d', localtime(time + 86400 *2)) unless ($todate);
$date=$fromdate;
$date=~s/\-//g;

chomp($fromdate);
chomp($todate);

print "[$fromdate][$todate][$date]\n";

my $partition_name = "uiadmin_logs_$date";
my $create_sql = qq{
   CREATE TABLE public.$partition_name PARTITION OF public.uiadmin_logs
       FOR VALUES FROM ('$fromdate') TO ('$todate')
   TABLESPACE pg_default;

   ALTER TABLE IF EXISTS public.$partition_name
       OWNER to qlrn;
   };

#------------------------------------------------------------------------
my $dbh = DBI->connect(
    $uidb,
    'qlrn', $password,
    { RaiseError => 1, AutoCommit => 1 }
) or die $DBI::errstr;

# Execute the SQL
$dbh->do($create_sql);

print "Partition table $partition_name created successfully.\n";

$dbh->disconnect;
