services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      postgresnet:
        ipv4_address: 172.19.0.2
    restart: always
    environment:
      - POSTGRES_USER=postgres        # Username for your postgres database
      - POSTGRES_PASSWORD=postgres    # Password for your postgres user
      - TZ=America/New_York
    ports:
      - '5433:5432'
    volumes:
      - /data/docker/data:/var/lib/postgresql/data
networks:
  postgresnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

